version: '3'

services:
  app:
    container_name: 'node-login'
    restart: 'always'
    env_file: .env
    build: .
    command: bash -c "sleep 10 && npm run migrate && npm run seed && npm start"
    ports: 
      - '9090:9090'
    depends_on:
      - 'db'
  
  db:
    container_name: 'postgres'
    restart: 'unless-stopped'
    image: 'postgres'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}

